const ROLES = {
    CLIENT: 'CLIENT',
    FREELANCER: 'FREELANCER',
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN: 'ADMIN',
    MODERATOR: 'MODERATOR',
    FINANCE_ADMIN: 'FINANCE_ADMIN',
    SUPPORT_ADMIN: 'SUPPORT_ADMIN',
    VERIFICATION_ADMIN: 'VERIFICATION_ADMIN'
};

const ADMIN_ROLES = [
    ROLES.SUPER_ADMIN,
    ROLES.ADMIN,
    ROLES.MODERATOR,
    ROLES.FINANCE_ADMIN,
    ROLES.SUPPORT_ADMIN,
    ROLES.VERIFICATION_ADMIN
];

module.exports = { ROLES, ADMIN_ROLES };
